import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {stages,allLessons,conceptCards,skillMatrix,tools,resourceLibrary,projectLadder,methodology} from './data/curriculum.js';
import './styles.css';

const ICONS={
 dashboard:'<path d="M4 4h16v16H4z"/><path d="M8 15v-3M12 15V8M16 15v-5"/>',
 skills:'<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v15H6.5A2.5 2.5 0 0 0 4 20.5z"/><path d="M4 5.5v15M8 7h8M8 10h6"/>',
 tools:'<rect x="4" y="4" width="12" height="10" rx="1.5"/><path d="M8 18h8M10 14v4M18 14l2 2-3 3-2-2z"/>',
 resources:'<path d="M4 7.5 12 4l8 3.5v9L12 20l-8-3.5z"/><path d="M8 9l8 3.5M12 20v-7.5M16 7l-8 4"/>',
 projects:'<circle cx="9" cy="7" r="3"/><path d="M3.5 19c.5-3.5 2.5-5 5.5-5s5 1.5 5.5 5M15 10h5M17.5 7.5v5"/>',
 learning:'<path d="M4 5h8a3 3 0 0 1 3 3v11H7a3 3 0 0 0-3 3z"/><path d="M20 5h-5v14h5a3 3 0 0 1 3 3V8a3 3 0 0 0-3-3z"/><path d="M7 9h5M7 12h5"/>',
 stages:'<rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/><path d="M10 7h4M7 10v4M17 10v4M10 17h4"/>',
 collapse:'<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M9 4v16M13 9l3 3-3 3"/>',
 theme:'<path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6l1.4 1.4M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4"/><circle cx="12" cy="12" r="3.5"/>',
 search:'<circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/>'
};
function Icon({name,size=20}){return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" dangerouslySetInnerHTML={{__html:ICONS[name]||''}}/>}
const LESSON_COLORS={1:['#20E3E6','#39D5C6'],2:['#35C9FF','#7BE0FF'],3:['#4D7CFF','#8EADFF'],4:['#6675FF','#9AA4FF'],5:['#7C5CFF','#B59AFF'],6:['#9B6BFF','#C7A8FF'],7:['#C18CFF','#E0C8FF'],8:['#FF3EA5','#FF78AC'],9:['#FF5C9A','#FF9BBD'],10:['#FF78AC','#FFC1D6'],11:['#FF8A78','#FFB09F'],12:['#FFB38A','#FFD0B8'],13:['#FFE0A3','#FFF0C9'],14:['#FFD166','#FFE6A3'],15:['#39D5C6','#82F5D6']};
const lessonStyle=num=>{const [a,b]=LESSON_COLORS[num]||LESSON_COLORS[1];return {'--lesson-a':a,'--lesson-b':b};};
function WordHeading({children}){const words=String(children).trim().split(/\s+/);if(words.length<=1)return <>{words[0]||''}</>;return <>{words.map((word,i)=><span key={i} className={i===0?'word-first':i===1?'word-second':'word-third'}>{i>0&&i<words.length?' ':''}{word}</span>)}</>}
const TOP_ITEMS=[['dashboard','Roadmap Overview'],['skills','Skill Matrix','skill-matrix'],['tools','Tools Roadmap','tools'],['resources','Resource Library','resources'],['projects','Project Ladder','projects'],['learning','Learning System','methodology']];
function App(){const [view,setView]=useState({view:'dashboard'});const [collapsed,setCollapsed]=useState(()=>localStorage.getItem('ard_sidebar_collapsed')==='1');const [collapsedMenuOpen,setCollapsedMenuOpen]=useState(false);const [theme,setTheme]=useState(()=>localStorage.getItem('ard_curriculum_theme')||'dark');const [progress,setProgress]=useState(()=>{try{return JSON.parse(localStorage.getItem('ard_curriculum_progress_v1'))||{}}catch{return {}}});const [query,setQuery]=useState('');useEffect(()=>{document.body.dataset.theme=theme;localStorage.setItem('ard_curriculum_theme',theme)},[theme]);useEffect(()=>{localStorage.setItem('ard_sidebar_collapsed',collapsed?'1':'0');if(!collapsed)setCollapsedMenuOpen(false)},[collapsed]);useEffect(()=>{localStorage.setItem('ard_curriculum_progress_v1',JSON.stringify(progress))},[progress]);const done=allLessons.filter(l=>progress[l.id]).length;const navigate=v=>{setView(v);setQuery('');if(window.innerWidth<=520)setCollapsedMenuOpen(false)};const toggleDone=id=>setProgress(p=>({...p,[id]:!p[id]}));return <div className={'app-shell '+(collapsed?'is-collapsed ':'')+(collapsedMenuOpen?'collapsed-menu-open':'')}><Topbar theme={theme} setTheme={setTheme} done={done} query={query} setQuery={setQuery} navigate={navigate}/><Sidebar collapsed={collapsed} setCollapsed={setCollapsed} collapsedMenuOpen={collapsedMenuOpen} setCollapsedMenuOpen={setCollapsedMenuOpen} view={view} navigate={navigate} progress={progress}/><main className="main" onClick={e=>{if(!collapsed&&window.innerWidth<=520&&!e.target.closest('.sidebar'))setCollapsed(true)}}><div className="main-inner"><RouterView view={view} navigate={navigate} progress={progress} toggleDone={toggleDone}/></div></main></div>}
function Topbar({theme,setTheme,done,query,setQuery,navigate}){const results=useMemo(()=>{if(query.trim().length<2)return [];const q=query.toLowerCase();const out=[];stages.forEach(s=>{if((s.title+' '+s.objective).toLowerCase().includes(q))out.push({type:'Stage',title:s.title,view:{view:'stage',stage:s.id}})});allLessons.forEach(l=>{if((l.title+' '+l.what+' '+l.module).toLowerCase().includes(q))out.push({type:'Lesson',title:l.title,view:{view:'lesson',id:l.id}})});conceptCards.forEach(c=>{if((c.title+' '+c.what+' '+c.module).toLowerCase().includes(q))out.push({type:'Concept',title:c.title,view:{view:'concept',id:c.id}})});tools.forEach(t=>{if((t.name+' '+t.purpose).toLowerCase().includes(q))out.push({type:'Tool',title:t.name,view:{view:'tools'}})});resourceLibrary.forEach(r=>{if((r.title+' '+r.topic).toLowerCase().includes(q))out.push({type:'Resource',title:r.title,view:{view:'resources'}})});return out.slice(0,20)},[query]);return <header className="topbar"><div className="brand"><span className="dot"/><span className="full">The ARD Curriculum</span><span className="compact">ARD</span></div><div className="search-wrap"><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search lessons, stages, resources, tools…" autoComplete="off"/>{query.trim().length>=2&&<div className="search-results open">{results.length?results.map((r,i)=><button key={i} className="search-result-item" onClick={()=>navigate(r.view)}><span className="type">{r.type}</span><span className="title">{r.title}</span></button>):<div className="search-result-item">No results.</div>}</div>}</div><div className="topbar-right"><span className="progress-chip">{done} / {allLessons.length} lessons complete</span><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} title="Toggle dark/light mode" aria-label="Toggle dark/light mode"><Icon name="theme" size={18}/></button></div></header>}
function Sidebar({collapsed,setCollapsed,collapsedMenuOpen,setCollapsedMenuOpen,view,navigate,progress}){return <aside className={'sidebar '+(collapsedMenuOpen?'mobile-menu-open':'')} onClick={e=>{if(window.innerWidth<=520&&collapsed&&!e.target.closest('.sidebar-footer')){const item=e.target.closest('.nav-top-item');if(!item)setCollapsedMenuOpen(v=>!v)}}}><div className="rail-logo"><span className="rail-mark">ϟ</span><span className="rail-label">ARD</span></div><div className="sidebar-scroll"><div className="nav-section-label">Navigate</div>{TOP_ITEMS.map(([icon,label,id])=><button key={id||icon} className={'nav-top-item '+((view.view===(id||icon))?'active':'')} onClick={()=>navigate({view:id||icon})} title={label}><Icon name={icon}/><span>{label}</span></button>)}<div className="nav-section-label stages-label">Curriculum</div><button className={'nav-top-item stages-nav-item '+((view.view==='stages'||view.view==='stage'||view.view==='lesson'||view.view==='concept')?'active':'')} onClick={()=>navigate({view:'stages'})} title="Stages"><Icon name="stages" size={20}/><span>Stages</span></button></div><div className="sidebar-footer"><button className="collapse-btn" onClick={()=>setCollapsed(!collapsed)} title={collapsed?'Expand navigation':'Collapse navigation'} aria-label={collapsed?'Expand navigation':'Collapse navigation'}><Icon name="collapse" size={21}/><span>{collapsed?'':'Collapse sidebar'}</span></button></div></aside>}
function RouterView({view,navigate,progress,toggleDone}){switch(view.view){case'dashboard':return <Dashboard navigate={navigate} progress={progress}/>;case'stages':return <StagesView navigate={navigate} progress={progress}/>;case'stage':return <StageView id={view.stage} navigate={navigate} progress={progress}/>;case'lesson':return <LessonView id={view.id} navigate={navigate} progress={progress} toggleDone={toggleDone}/>;case'concept':return <ConceptView id={view.id} navigate={navigate}/>;case'skill-matrix':return <SkillMatrix/>;case'tools':return <Tools/>;case'resources':return <Resources/>;case'projects':return <Projects/>;case'methodology':return <Methodology/>;default:return <Dashboard navigate={navigate} progress={progress}/>}}
function Dashboard({navigate,progress}){const done=allLessons.filter(l=>progress[l.id]).length;return <><div className="dash-hero"><div className="eyebrow">ARD Curriculum · Personal Learning System</div><h1><WordHeading>Web Development → Full Stack → UI/UX → Software Engineering</WordHeading></h1><p>A complete, self-contained personal curriculum: 15 stages from absolute beginner to professional practical ability, with real lesson content, concept notes, a skill matrix, a tool roadmap, a resource library, and a 6-level project ladder.</p></div><div className="stat-row"><Stat n="15" label="Stages"/><Stat n={allLessons.length} label="Full lessons"/><Stat n={conceptCards.length} label="Concept notes"/><Stat n={done+'/'+allLessons.length} label="Your progress"/></div><div className="roadmap-flow">{stages.map(s=><button className="flow-stage" key={s.id} onClick={()=>navigate({view:'stage',stage:s.id})}><span className="fnum">{String(s.num).padStart(2,'0')}</span><div><div className="ftitle">{s.title}</div><div className="fobjective">{s.objective}</div></div><span className="flow-arrow">→</span></button>)}</div></>}
function Stat({n,label}){return <div className="stat-box"><div className="num">{n}</div><div className="label">{label}</div></div>}
function StagesView({navigate,progress}){const done=allLessons.filter(l=>progress[l.id]).length;return <div className="stages-index"><div className="stages-index-hero"><div className="eyebrow">ARD Curriculum · Curriculum Map</div><h1><WordHeading>The 15 Stages</WordHeading></h1><p>Explore the curriculum as a clear progression from absolute beginner to professional practical ability. Open a stage to see its objectives, skills, projects, lessons, and concept notes.</p><div className="stages-index-stats"><Stat n="15" label="Stages"/><Stat n={allLessons.length} label="Full lessons"/><Stat n={conceptCards.length} label="Concept notes"/><Stat n={done+'/'+allLessons.length} label="Completed"/></div></div><div className="stage-index-grid">{stages.map(s=>{const lessons=allLessons.filter(l=>l.stage===s.id),concepts=conceptCards.filter(c=>c.stage===s.id),complete=lessons.filter(l=>progress[l.id]).length;return <button className="stage-index-card" key={s.id} style={lessonStyle(s.num)} onClick={()=>navigate({view:'stage',stage:s.id})}><div className="stage-card-top"><span className="stage-card-num">{String(s.num).padStart(2,'0')}</span><span className="stage-card-arrow">→</span></div><h2>{s.title}</h2><p>{s.objective}</p><div className="stage-card-meta"><span>{lessons.length} {lessons.length===1?'lesson':'lessons'}</span><span>{concepts.length} {concepts.length===1?'concept':'concepts'}</span></div>{lessons.length>0&&<div className="stage-card-progress"><span style={{width:`${Math.round(complete/lessons.length*100)}%`}}/></div>}</button>})}</div></div>}
function StageView({id,navigate,progress}){const s=stages.find(x=>x.id===id);if(!s)return <p className="empty-note">Stage not found.</p>;const lessons=allLessons.filter(l=>l.stage===id),concepts=conceptCards.filter(c=>c.stage===id);return <div className="stage-view" style={lessonStyle(s.num)} data-stage={s.num}><button className="stage-back-btn" onClick={()=>navigate({view:'stages'})}>← All 15 stages</button><div className="stage-eyebrow">Stage {s.num} of 15</div><h1>{s.title}</h1><p className="lead">{s.objective}</p><div className="stage-meta-grid"><Meta title="Prerequisites" items={[s.prerequisites]}/><Meta title="Skills gained" items={s.skills}/><Meta title="Technologies" items={s.technologies}/><Meta title="Core concepts" items={s.concepts}/><Meta title="Projects" items={s.projects}/><Meta title="Assessments" items={s.assessments}/></div><Meta title="Resources" items={s.resources}/><div className="exit-box"><div className="label">Exit Criteria</div>{s.exitCriteria}</div>{lessons.length>0&&<><h2 className="subheading">Full Lessons in this Stage</h2>{lessons.map(l=><button className="content-link" key={l.id} onClick={()=>navigate({view:'lesson',id:l.id})}>→ {l.title}{progress[l.id]&&<span className="complete">complete</span>}</button>)}</>}{concepts.length>0&&<><h2 className="subheading">Concept Notes in this Stage</h2>{concepts.map(c=><button className="content-link" key={c.id} onClick={()=>navigate({view:'concept',id:c.id})}>→ {c.title}</button>)}</>}</div>}
function Meta({title,items}){if(!items?.length)return null;return <div className="meta-block"><h3>{title}</h3><ul>{items.map((i,n)=><li key={n}>{i}</li>)}</ul></div>}
function LessonView({id,navigate,progress,toggleDone}){const l=allLessons.find(x=>x.id===id);if(!l)return <p className="empty-note">Lesson not found.</p>;const stage=stages.find(s=>s.id===l.stage);return <div className="lesson-view" style={lessonStyle(stage?.num)} data-stage={stage?.num}><button className="stage-back-btn lesson-back-btn" onClick={()=>navigate({view:'stage',stage:l.stage})}>← {stage?.title||'Stage'}</button><div className="lesson-eyebrow">{stage?.title} · {l.module}</div><h1>{l.title}</h1><Section t="1. What is it?"><p>{l.what}</p></Section><Section t="2. Why does it matter?"><p>{l.why}</p></Section><Section t="3. Mental model"><p>{l.mentalModel}</p></Section><Section t="4. Core concepts"><ul>{l.coreConcepts.map((x,i)=><li key={i}>{x}</li>)}</ul></Section><Section t="5. Example"><pre>{l.example}</pre></Section><Section t="6. Code"><pre>{l.code}</pre></Section><Section t="7. Common mistakes"><ul>{l.commonMistakes.map((x,i)=><li key={i}>{x}</li>)}</ul></Section><Section t="8. Practice"><p>{l.practice}</p></Section><Section t="9. Challenge"><p>{l.challenge}</p></Section><Section t="10. Mini project"><p>{l.miniProject}</p></Section><Section t="11. Resources">{l.resources.map((r,i)=><div className="resource-item" key={i}><div className="rtitle"><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title}</a></div><div className="rnote">{r.note}</div></div>)}</Section><Section t="Mastery checklist"><ul className="mastery-list">{l.mastery.map((m,i)=><li key={i}><span>□</span><span>{m}</span></li>)}</ul></Section><div className="mark-complete-bar"><button className={'btn '+(progress[l.id]?'done':'')} onClick={()=>toggleDone(l.id)}>{progress[l.id]?'✓ Marked complete':'Mark lesson complete'}</button><button className="btn secondary" onClick={()=>navigate({view:'stage',stage:l.stage})}>Back to stage</button></div></div>}
function Section({t,children}){return <section className="lsection"><h2>{t}</h2>{children}</section>}
function ConceptView({id,navigate}){const c=conceptCards.find(x=>x.id===id);if(!c)return <p className="empty-note">Concept not found.</p>;const s=stages.find(x=>x.id===c.stage);return <><div className="lesson-eyebrow">{s?.title}</div><div className="concept-card" style={lessonStyle(s?.num)} data-stage={s?.num}><h2>{c.title}</h2><div className="cmod">{c.module}</div><h4>What is it?</h4><p>{c.what}</p><h4>Why it matters</h4><p>{c.why}</p><h4>Key points</h4><ul>{c.keyPoints.map((x,i)=><li key={i}>{x}</li>)}</ul><h4>Resource</h4><p><a href={c.resource.url} target="_blank" rel="noopener noreferrer">{c.resource.title}</a></p></div><button className="btn secondary" onClick={()=>navigate({view:'stage',stage:c.stage})}>Back to stage</button></>}
function SkillMatrix(){return <Page title="Skill Matrix" subtitle={'What "beginner," "intermediate," "advanced," and "professional" actually look like, per skill.'}><div className="table-wrap"><table className="data-table"><thead><tr>{['Skill','Category','Beginner','Intermediate','Advanced','Professional','Prerequisites','Projects'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{skillMatrix.map((r,i)=><tr key={i}>{['skill','category','beginner','intermediate','advanced','professional','prerequisites','projects'].map(k=><td key={k}>{k==='skill'?<b>{r[k]}</b>:r[k]}</td>)}</tr>)}</tbody></table></div></Page>}
function Tools(){return <Page title="Tools Roadmap" subtitle="What to install and when — deliberately minimal, to avoid tool overload.">{tools.map((t,i)=><div className="tool-card" key={i}><h3>{t.name}<span className="tool-cost">{t.cost}</span></h3><div className="trow"><b>Purpose:</b> {t.purpose}</div><div className="trow"><b>Why:</b> {t.why}</div><div className="trow"><b>When to learn it:</b> {t.when}</div><div className="trow"><b>Alternatives:</b> {t.alternatives}</div></div>)}</Page>}
function Resources(){return <Page title="Resource Library" subtitle={`${resourceLibrary.length} vetted, high-quality resources — official docs and open, reputable courses first.`}><div className="table-wrap"><table className="data-table"><thead><tr>{['Title','Creator','Type','Difficulty','Cost','Topic','Why it\'s useful'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{resourceLibrary.map((r,i)=><tr key={i}><td><a href={r.url} target="_blank" rel="noopener noreferrer"><b>{r.title}</b></a></td><td>{r.creator}</td><td>{r.type}</td><td>{r.difficulty}</td><td>{r.cost}</td><td>{r.topic}</td><td>{r.why}</td></tr>)}</tbody></table></div></Page>}
function Projects(){return <Page title="Project Ladder" subtitle="Six levels, from a static bio page to a shipped capstone. Build the projects; don't just read about them.">{projectLadder.map(lvl=><div className="level-block" key={lvl.level}><span className="level-tag">Level {lvl.level}</span><h2>{lvl.title}</h2><p className="muted">{lvl.objective}</p><p className="muted small"><b>Prerequisites:</b> {lvl.prerequisites}</p>{lvl.projects.map((p,i)=><div className="project-card" key={i}><h3>{p.name}</h3><div className="project-fields">{[['features','Features'],['tech','Tech requirements'],['ui','UI requirements'],['db','Database'],['testing','Testing'],['deployment','Deployment'],['stretch','Stretch goal'],['evaluation','Evaluation criteria']].map(([k,label])=><div key={k}><div className="pf-label">{label}</div><div>{p[k]}</div></div>)}</div></div>)}</div>)}</Page>}
function Methodology(){return <Page title="Learning System" subtitle="The methodology behind every stage and lesson in this curriculum."><div className="concept-card"><h4>The loop</h4><p className="loop">{methodology.loop.join(' → ')}</p><p>{methodology.description}</p></div><div className="concept-card"><h4>Practices</h4><ul>{methodology.practices.map((p,i)=><li key={i}>{p}</li>)}</ul></div><div className="concept-card"><h4>When to move to the next stage</h4><p>{methodology.masteryRequirement}</p></div></Page>}
function Page({title,subtitle,children}){return <><div className="dash-hero"><div className="eyebrow">ARD Curriculum</div><h1><WordHeading>{title}</WordHeading></h1><p>{subtitle}</p></div>{children}</>}
createRoot(document.getElementById('root')).render(<App/>);