import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {stages, allLessons, conceptCards, skillMatrix, tools, resourceLibrary, projectLadder, methodology} from './data/curriculum.js';
import './styles.css';

const I=({children,size=18,stroke=1.8})=><svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={stroke} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{children}</svg>;
const Icons={
 dashboard:()=> <I><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><path d="M14 17h7M17.5 14v7"/></I>,
 matrix:()=> <I><path d="M4 4h16v16H4z"/><path d="M8 4v16M16 4v16M4 8h16M4 16h16"/></I>,
 tools:()=> <I><path d="M14.7 6.3a4 4 0 0 0-5.1 5.1L4 17l3 3 5.6-5.6a4 4 0 0 0 5.1-5.1l-2.1 2.1-2.2-2.2z"/><path d="M14 4h6v6"/></I>,
 resources:()=> <I><path d="M4 5a2 2 0 0 1 2-2h14v17H6a2 2 0 0 0-2 2z"/><path d="M4 5v15M8 7h8M8 11h8"/></I>,
 projects:()=> <I><circle cx="12" cy="6" r="3"/><path d="M5 21a7 7 0 0 1 14 0M17 13l2 2 3-4"/></I>,
 learning:()=> <I><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H12v17H6.5A2.5 2.5 0 0 0 4 22z"/><path d="M12 3h5.5A2.5 2.5 0 0 1 20 5.5V22h-2.5A2.5 2.5 0 0 0 15 19.5H12z"/><path d="M7 7h2M7 11h2"/></I>,
 search:()=> <I><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></I>,
 chevron:()=> <I><path d="m9 18 6-6-6-6"/></I>,
 down:()=> <I><path d="m6 9 6 6 6-6"/></I>,
 rail:()=> <I><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M8 4v16M13 12h5"/></I>,
 sun:()=> <I><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></I>,
 moon:()=> <I><path d="M20.8 15.2A8.5 8.5 0 0 1 8.8 3.2 8.5 8.5 0 1 0 20.8 15.2z"/></I>,
 check:()=> <I><path d="m5 12 4 4L19 6"/></I>,
 external:()=> <I size={14}><path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h5"/></I>
};
const nav=[['dashboard','Dashboard','Overview'],['matrix','Skill Matrix','Capabilities'],['tools','Tools Roadmap','Stack'],['resources','Resource Library','References'],['projects','Project Ladder','Projects'],['learning','Learning System','Method']];
const stageById=Object.fromEntries(stages.map(s=>[s.id,s]));
const lessonById=Object.fromEntries(allLessons.map(l=>[l.id,l]));
function App(){
 const [collapsed,setCollapsed]=useState(false); const [view,setView]=useState({type:'dashboard'}); const [theme,setTheme]=useState(()=>localStorage.getItem('ard-theme')||'dark'); const [query,setQuery]=useState(''); const [expanded,setExpanded]=useState({}); const [done,setDone]=useState(()=>JSON.parse(localStorage.getItem('ard-done')||'{}'));
 useEffect(()=>{document.body.dataset.theme=theme;localStorage.setItem('ard-theme',theme)},[theme]);
 useEffect(()=>localStorage.setItem('ard-done',JSON.stringify(done)),[done]);
 const completed=Object.values(done).filter(Boolean).length;
 const open=(type,id)=>setView({type,id});
 const toggleDone=id=>setDone(d=>({...d,[id]:!d[id]}));
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return allLessons.filter(l=>(l.title+' '+l.stage+' '+(l.description||'')).toLowerCase().includes(q)).slice(0,8)},[query]);
 return <div className={`app ${collapsed?'is-collapsed':''}`}>
  <header className="topbar"><div className="brand"><div className="brand-mark">⚡</div><span>The ARD Curriculum</span></div><div className="search"><Icons.search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search lessons, stages, resources, tools…"/>{filtered.length>0&&<div className="search-results">{filtered.map(l=><button key={l.id} onClick={()=>{open('lesson',l.id);setQuery('')}}><strong>{l.title}</strong><small>{l.stage}</small></button>)}</div>}</div><div className="top-actions"><span className="progress-chip">{completed} / {allLessons.length} lessons complete</span><button className="icon-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')} title="Toggle theme">{theme==='dark'?<Icons.sun/>:<Icons.moon/>}</button></div></header>
  <aside className="sidebar"><div className="sidebar-nav">{nav.map(([icon,label,sub])=><button key={label} className={`nav-item ${view.type===icon?'active':''}`} onClick={()=>open(icon)} title={collapsed?label:''}>{React.createElement(Icons[icon])}<span><b>{label}</b><small>{sub}</small></span></button>)}<div className="stage-label">CURRICULUM</div>{stages.map(s=><div key={s.id} className="stage-wrap"><button className={`nav-item stage-item ${view.type==='stage'&&view.id===s.id?'active':''}`} onClick={()=>open('stage',s.id)} title={collapsed?s.title:''}><span className="stage-num">{String(s.num).padStart(2,'0')}</span><span><b>{s.title}</b><small>{s.lessons?.length||0} lessons</small></span><i onClick={e=>{e.stopPropagation();setExpanded(x=>({...x,[s.id]:!x[s.id]}))}}>{expanded[s.id]?<Icons.down/>:<Icons.chevron/>}</i></button>{expanded[s.id]&&!collapsed&&<div className="lesson-tree">{(s.lessons||[]).map(id=>lessonById[id]&&<button key={id} onClick={()=>open('lesson',id)}>{lessonById[id].title}</button>)}</div>}</div>)}</div><button className="collapse-btn" onClick={()=>setCollapsed(x=>!x)} title={collapsed?'Expand sidebar':'Collapse sidebar'}><Icons.rail/></button></aside>
  <main className="main"><div className="main-inner">{view.type==='dashboard'&&<Dashboard open={open} completed={completed}/>} {view.type==='stage'&&<StageView id={view.id} open={open} done={done}/>} {view.type==='lesson'&&<LessonView id={view.id} done={done} toggleDone={toggleDone}/>} {view.type==='matrix'&&<SkillMatrix/>} {view.type==='tools'&&<ToolsView/>} {view.type==='resources'&&<Resources/>} {view.type==='projects'&&<Projects/>} {view.type==='learning'&&<Learning/>}</div></main>
 </div>
}
function PageHeader({eyebrow,title,text}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div></div>}
function Dashboard({open,completed}){return <><PageHeader eyebrow="THE ARD CURRICULUM" title="Roadmap Overview" text="A structured path from computer fundamentals to full-stack engineering, UI/UX design, and software engineering."/><section className="hero-grid"><div className="hero-card"><div className="eyebrow">15 STAGES</div><h2>Build the complete stack.</h2><p>Learn in sequence, practice deliberately, and ship projects that prove the skill.</p><button className="primary" onClick={()=>open('stage',stages[0].id)}>Start with Stage 01 <Icons.chevron/></button></div><div className="stat-card"><strong>{completed}</strong><span>Lessons completed</span></div><div className="stat-card"><strong>{allLessons.length}</strong><span>Detailed lessons</span></div></section><div className="section-title"><h2>Curriculum stages</h2><span>01 — 15</span></div><div className="stage-grid">{stages.map(s=><button className="stage-card" key={s.id} onClick={()=>open('stage',s.id)}><span className="stage-number">{String(s.num).padStart(2,'0')}</span><h3>{s.title}</h3><p>{s.objective}</p><span className="card-link">Open stage <Icons.chevron/></span></button>)}</div></>}
function StageView({id,open,done}){const s=stageById[id]; if(!s)return null; return <><PageHeader eyebrow={`STAGE ${String(s.num).padStart(2,'0')}`} title={s.title} text={s.objective}/><div className="info-grid"><Info title="Prerequisites" items={[s.prerequisites]}/><Info title="Core skills" items={s.skills}/><Info title="Technologies" items={s.technologies}/></div><div className="content-grid"><section className="panel"><div className="section-title"><h2>Lessons</h2><span>{s.lessons?.length||0}</span></div>{(s.lessons||[]).map(id=>{const l=lessonById[id];return l&&<button className="lesson-row" key={id} onClick={()=>open('lesson',id)}><span className={`lesson-check ${done[id]?'done':''}`}>{done[id]&&<Icons.check/>}</span><span><b>{l.title}</b><small>{l.description||''}</small></span><Icons.chevron/></button>})}</section><section className="panel"><div className="section-title"><h2>Projects & exit criteria</h2></div><ul>{(s.projects||[]).map(x=><li key={x}>{x}</li>)}</ul><div className="exit"><b>Exit criteria</b><p>{s.exitCriteria}</p></div></section></div></>}
function LessonView({id,done,toggleDone}){const l=lessonById[id];if(!l)return null;return <><PageHeader eyebrow={l.stage||'LESSON'} title={l.title} text={l.description||''}/><div className="lesson-layout"><article className="lesson-content"><div className="panel prose"><h2>What you will learn</h2>{l.content? <div dangerouslySetInnerHTML={{__html:l.content}}/>:<p>Work through the concepts, exercises, and project requirements for this lesson.</p>}</div></article><aside className="lesson-aside"><button className={`complete-btn ${done[id]?'completed':''}`} onClick={()=>toggleDone(id)}>{done[id]?<><Icons.check/> Completed</>:<>Mark complete</>}</button><div className="panel"><b>Lesson navigation</b><div className="mini-list">{allLessons.slice(Math.max(0,allLessons.findIndex(x=>x.id===id)-2),allLessons.findIndex(x=>x.id===id)+3).map(x=><button key={x.id} onClick={()=>location.hash=x.id}>{x.title}</button>)}</div></div></aside></div></>}
function Info({title,items=[]}){return <div className="panel"><div className="eyebrow">{title}</div><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></div>}
function SkillMatrix(){return <><PageHeader eyebrow="CAPABILITY MAP" title="Skill Matrix" text="The capabilities the curriculum is designed to develop across the stack."/><div className="table-wrap panel"><table><thead><tr><th>Skill</th><th>Foundation</th><th>Working</th><th>Advanced</th></tr></thead><tbody>{skillMatrix.map((r,i)=><tr key={i}><td>{r.skill||r.name||Object.values(r)[0]}</td><td>{r.foundation||'—'}</td><td>{r.working||'—'}</td><td>{r.advanced||'—'}</td></tr>)}</tbody></table></div></>}
function ToolsView(){return <><PageHeader eyebrow="STACK" title="Tools Roadmap" text="The tools and technologies introduced throughout the curriculum."/><div className="card-grid">{tools.map((t,i)=><div className="panel tool-card" key={i}><div className="tool-icon"><Icons.tools/></div><h3>{t.name||t.title}</h3><p>{t.description||t.why||''}</p></div>)}</div></>}
function Resources(){return <><PageHeader eyebrow="REFERENCES" title="Resource Library" text="Curated references to support the curriculum."/><div className="resource-list">{resourceLibrary.map((r,i)=><div className="panel resource-row" key={i}><div><h3>{r.title||r.name}</h3><p>{r.description||r.type||''}</p></div>{r.url&&<a href={r.url} target="_blank" rel="noreferrer"><Icons.external/></a>}</div>)}</div></>}
function Projects(){return <><PageHeader eyebrow="SHIP IT" title="Project Ladder" text="Projects increase in scope as your engineering ability grows."/><div className="ladder">{projectLadder.map((p,i)=><div className="panel ladder-row" key={i}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{p.title||p.name}</h3><p>{p.description||''}</p></div></div>)}</div></>}
function Learning(){return <><PageHeader eyebrow="METHOD" title="Learning System" text={methodology?.intro||'A repeatable system for learning, building, reviewing, and shipping.'}/><div className="card-grid">{Object.entries(methodology||{}).filter(([k])=>k!=='intro').map(([k,v])=><div className="panel" key={k}><div className="eyebrow">{k.replace(/[-_]/g,' ')}</div><p>{typeof v==='string'?v:JSON.stringify(v)}</p></div>)}</div></>}

function start(){React.createElement;createRoot(document.getElementById('root')).render(<App/>)}
start();
